server:
  port: 8080
javax:
  sql:
    DataSource:
      sampleDataSource:
        dataSourceClassName: com.mysql.cj.jdbc.MysqlDataSource
        dataSource:
          url: jdbc:mysql://localhost/sample
          user: sample
          password: sample
          serverTimezone: America/Lima
          useSSL: false
