kumuluzee:
  datasources:
    - jndi-name: jdbc/SampleDS
      driver-class: com.mysql.cj.jdbc.MysqlDataSource
      connection-url: jdbc:mysql://localhost/sample?serverTimezone=America/Lima&useSSL=false
      username: sample
      password: sample
      pool:
        auto-commit: true
        flush-on-close: false 
